[theme]
primaryColor = "#187B91"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F4F7FA"
textColor = "#183B4E"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
